PR for HomeWork #3 (Cloud bastion)
otus-devops-2019-05/vvorontsov_infra pull request #2
Opened 2019-06-21 16:17 UTC by vvorontsov

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Создан аккаунт в GCP
- Создано 2 инстанса VM: bastion и someinternalhost
- Настроено подключение по ssh к someinternalhost через bastion
- На bastion поднят VPN-сервер pritunl
- Настроено подключение к someinternalhost через VPN-туннель

## Как проверить работоспособность:
 - Тесты Travis CI прошли успешно

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2019-06-21 16:58 UTC, mrgreyves requested changes
Здравствуйте!) Постарайтесь починить тесты тревиса. Скорее всего ошибка в описании хостов в ридми.

2019-06-21 16:58 UTC, mrgreyves commented on README.md
> +https://wiki.gentoo.org/wiki/SSH_jump_host#Setup_2
Хорошо что оставляете ссылки на документацию =)

2019-06-21 19:06 UTC, vvorontsov commented on README.md
> +https://wiki.gentoo.org/wiki/SSH_jump_host#Setup_2
Добрый вечер! Я удалил раньше времени виртуалки, поторопился) Теперь всё заново настраиваю.

2019-06-21 19:40 UTC, vvorontsov commented on README.md
> +https://wiki.gentoo.org/wiki/SSH_jump_host#Setup_2
Все настроил по новой, должно быть ок.

2019-06-21 19:46 UTC, vvorontsov commented on README.md
> +https://wiki.gentoo.org/wiki/SSH_jump_host#Setup_2
https://travis-ci.com/otus-devops-2019-05/vvorontsov_infra

2019-06-27 09:48 UTC, mrgreyves approved these changes
Здравствуйте!) Вполне возможно что во время тестирования инфраструктура была погашена. Для этого дз это критично. В остальном задание было выполнено корректно. ДЗ принимаю!=)

2019-06-27 09:51 UTC, merged